version: '3.8'
name: 'egglocke-maker'

services:
  pkhex:
    build: ./pkhex
    container_name: pkhex_container
    hostname: pkhex_host
    platform: linux/amd64
    ports:
      - "1235"
    networks:
      app_network:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    hostname: server_host
    ports:
      - "127.0.0.1:8443:8443"
    networks:
      app_network:

networks:
  app_network:
    driver: bridge

