# Generated by Django 5.0.6 on 2024-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0004_alter_submitter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_EV',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_IV',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_OT',
            field=models.CharField(default='Red', max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_OTGender',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_ability',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_ball',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_language',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_moves',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_movespp',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_nature',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_nickname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
