# Generated by Django 5.0.6 on 2024-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0006_alter_pokemon_pokemon_ev_alter_pokemon_pokemon_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_moves',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_movespp',
            field=models.JSONField(default=[]),
        ),
    ]
