# Generated by Django 5.1.6 on 2025-02-13 04:56

import django.db.models.deletion
import pokepoll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tripcode', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_nickname', models.CharField(default='', max_length=10)),
                ('pokemon_species', models.IntegerField(default=1)),
                ('pokemon_ball', models.IntegerField(default=1)),
                ('pokemon_language', models.IntegerField(default=2)),
                ('pokemon_ability', models.IntegerField(default=1)),
                ('pokemon_nature', models.IntegerField(default=1)),
                ('pokemon_OT', models.CharField(default='Red', max_length=10)),
                ('pokemon_OTGender', models.IntegerField(default=1)),
                ('pokemon_IV', models.JSONField(default=[31, 31, 31, 31, 31, 31])),
                ('pokemon_EV', models.JSONField(default=[0, 0, 0, 0, 0, 0])),
                ('pokemon_moves', models.JSONField(default=[1])),
                ('pokemon_movespp', models.JSONField(default=[0])),
                ('pokemon_held_item', models.IntegerField(default=0)),
                ('pokemon_is_shiny', models.BooleanField(default=False)),
                ('pokemon_intended_generation', models.IntegerField(choices=[(1, 'Gen 1'), (2, 'Gen 2'), (3, 'Gen 3'), (4, 'Gen 4'), (5, 'Gen 5'), (6, 'Gen 6'), (7, 'Gen 7'), (8, 'Gen 8')], default=4)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('upvotes', models.IntegerField(default=0)),
                ('submitter', models.ForeignKey(default=pokepoll.models.Submitter.get_default_parent_key, on_delete=django.db.models.deletion.CASCADE, to='pokepoll.submitter')),
            ],
        ),
    ]
