# Generated by Django 5.0.6 on 2024-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Pokemon',
        ),
    ]
