# Generated by Django 5.0.6 on 2024-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0003_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
