# Generated by Django 5.0.6 on 2024-06-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0010_pokemon_pokemon_held_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_is_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_moves',
            field=models.JSONField(default=[1]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_movespp',
            field=models.JSONField(default=[0]),
        ),
    ]
