# Generated by Django 5.0.6 on 2024-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0011_pokemon_pokemon_is_shiny_alter_pokemon_pokemon_moves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_generations',
            field=models.JSONField(default=[4]),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_intended_generation',
            field=models.IntegerField(default=1),
        ),
    ]
