# Generated by Django 5.0.6 on 2024-06-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0012_pokemon_pokemon_generations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_generations',
            new_name='pokemon_compatible_generations',
        ),
    ]
