# Generated by Django 5.0.6 on 2024-06-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0013_rename_pokemon_generations_pokemon_pokemon_compatible_generations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_intended_generation',
            field=models.IntegerField(choices=[(1, 'Gen 1'), (2, 'Gen 2'), (3, 'Gen 3'), (4, 'Gen 4'), (5, 'Gen 5'), (6, 'Gen 6'), (7, 'Gen 7'), (8, 'Gen 8')], default=4),
        ),
    ]
