# Generated by Django 5.0.6 on 2024-07-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokepoll', '0014_alter_pokemon_pokemon_intended_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_compatible_generations',
        ),
    ]
